# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3be9f4d6-40da-4033-9f85-74b144891c9d";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."root-crypt-p3".device = "/dev/disk/by-uuid/acc397b2-a14a-4618-a32e-a35ef6880bd8";

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/3be9f4d6-40da-4033-9f85-74b144891c9d";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/3be9f4d6-40da-4033-9f85-74b144891c9d";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/3be9f4d6-40da-4033-9f85-74b144891c9d";
      fsType = "btrfs";
      options = [ "subvol=@var_log" ];
    };

  fileSystems."/tmp" =
    { device = "/dev/disk/by-uuid/3be9f4d6-40da-4033-9f85-74b144891c9d";
      fsType = "btrfs";
      options = [ "subvol=@tmp" ];
    };

  fileSystems."/srv" =
    { device = "/dev/disk/by-uuid/3be9f4d6-40da-4033-9f85-74b144891c9d";
      fsType = "btrfs";
      options = [ "subvol=@srv" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/3be9f4d6-40da-4033-9f85-74b144891c9d";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/88C0-A114";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/4528549c-b853-46df-a147-3cc2f4b6b5cb"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp170s0.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
